version: '3.8'

services:
  web:
    build: .
    container_name: ordering_plan_container
    # ★重要：iMacのフォルダとDockerの中を繋ぐことで、データ（db.sqlite3）をそのまま引き継ぎます
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    restart: always