# Generated by Django 6.0.5 on 2026-06-01 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='商品コード')),
                ('name', models.CharField(max_length=255, verbose_name='商品名')),
                ('price', models.IntegerField(blank=True, default=0, null=True, verbose_name='標準原価')),
                ('supplier', models.CharField(blank=True, max_length=100, null=True, verbose_name='仕入先')),
                ('lead_time', models.IntegerField(default=30, help_text='発注から納品までの標準日数', verbose_name='リードタイム（日数）')),
                ('order_lot', models.IntegerField(default=1, help_text='最低発注単位', verbose_name='発注ロット')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='発注数量')),
                ('status', models.CharField(choices=[('planning', '計画中（未承認）'), ('ordered', '発注済'), ('arrived', '納品済')], default='planning', max_length=20, verbose_name='ステータス')),
                ('order_date', models.DateField(blank=True, null=True, verbose_name='発注日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='データ作成日時')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '発注データ',
                'verbose_name_plural': '発注データ',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_quantity', models.IntegerField(default=0, verbose_name='現在庫数')),
                ('safety_stock', models.IntegerField(default=0, help_text='この数を下回ったら発注警告', verbose_name='安全在庫数')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '在庫',
                'verbose_name_plural': '在庫',
            },
        ),
        migrations.CreateModel(
            name='SalesHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_date', models.DateField(verbose_name='受注日（販売日）')),
                ('quantity', models.IntegerField(verbose_name='受注数量')),
                ('customer', models.CharField(blank=True, max_length=100, null=True, verbose_name='顧客・卸先名')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '受注履歴',
                'verbose_name_plural': '受注履歴',
                'ordering': ['-sold_date'],
            },
        ),
    ]
