# Generated by Django 6.0.5 on 2026-06-01 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleshistory',
            name='sales_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='日次販売履歴ID'),
        ),
    ]
