# Generated by Django 6.0.5 on 2026-06-03 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_saleshistory_sales_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '発注計画', 'verbose_name_plural': '発注計画'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
        migrations.AddField(
            model_name='product',
            name='trend_max',
            field=models.FloatField(default=2.0, help_text='急増時の最大倍率（例: 2.0なら最大200%まで許容）', verbose_name='トレンド上限'),
        ),
        migrations.AddField(
            model_name='product',
            name='trend_min',
            field=models.FloatField(default=0.5, help_text='激減時の最小倍率（例: 0.5なら最低50%で底打ち）', verbose_name='トレンド下限'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='safety_stock',
            field=models.IntegerField(default=0, verbose_name='安全在庫数'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('計画中', '計画中'), ('発注済', '発注済'), ('入庫済', '入庫済')], default='計画中', max_length=10, verbose_name='ステータス'),
        ),
        migrations.AlterField(
            model_name='product',
            name='lead_time',
            field=models.IntegerField(default=30, verbose_name='リードタイム（日数）'),
        ),
        migrations.AlterField(
            model_name='product',
            name='order_lot',
            field=models.IntegerField(default=1, verbose_name='発注ロット'),
        ),
        migrations.AlterField(
            model_name='saleshistory',
            name='customer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='顧客名'),
        ),
        migrations.AlterField(
            model_name='saleshistory',
            name='sold_date',
            field=models.DateField(verbose_name='受注日'),
        ),
        migrations.CreateModel(
            name='ArrivalSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_date', models.DateField(verbose_name='入荷予定日')),
                ('quantity', models.IntegerField(verbose_name='入荷予定数量')),
                ('status', models.CharField(choices=[('確定', '確定'), ('高確度', '高確度'), ('希望', '希望')], max_length=10, verbose_name='確度')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '入荷予定',
                'verbose_name_plural': '入荷予定',
            },
        ),
        migrations.CreateModel(
            name='ShipmentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_date', models.DateField(verbose_name='出荷予定日')),
                ('quantity', models.IntegerField(verbose_name='出荷予定数量')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '出荷予定',
                'verbose_name_plural': '出荷予定',
            },
        ),
    ]
