# Generated by Django 6.0.5 on 2026-06-03 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_order_options_remove_order_order_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arrivalschedule',
            options={'verbose_name': '入荷予定・発注残', 'verbose_name_plural': '入荷予定・発注残'},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': '現在庫', 'verbose_name_plural': '現在庫'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '商品マスタ', 'verbose_name_plural': '商品マスタ'},
        ),
        migrations.AlterModelOptions(
            name='saleshistory',
            options={'ordering': ['-sold_date'], 'verbose_name': '日次販売履歴', 'verbose_name_plural': '日次販売履歴'},
        ),
        migrations.AddField(
            model_name='inventory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='データ更新日時'),
        ),
        migrations.AlterField(
            model_name='arrivalschedule',
            name='status',
            field=models.CharField(choices=[('確定', '確定'), ('高確度', '高確度'), ('希望', '希望')], max_length=10, verbose_name='確度ステータス'),
        ),
        migrations.AlterField(
            model_name='product',
            name='trend_max',
            field=models.FloatField(default=2.0, help_text='急増時の最大倍率', verbose_name='トレンド上限'),
        ),
        migrations.AlterField(
            model_name='product',
            name='trend_min',
            field=models.FloatField(default=0.5, help_text='激減時の最小倍率', verbose_name='トレンド下限'),
        ),
        migrations.AlterField(
            model_name='saleshistory',
            name='customer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='得意先名'),
        ),
        migrations.AlterField(
            model_name='saleshistory',
            name='quantity',
            field=models.IntegerField(verbose_name='販売数'),
        ),
        migrations.AlterField(
            model_name='saleshistory',
            name='sold_date',
            field=models.DateField(verbose_name='伝票日付'),
        ),
    ]
