# Generated by Django 6.0.5 on 2026-06-10 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_arrivalschedule_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='CSVの列名と完全一致させます', max_length=100, unique=True, verbose_name='倉庫名')),
                ('is_transit', models.BooleanField(default=False, help_text='名前に「移動中」が含まれる場合は自動でチェックが入ります', verbose_name='移動中フラグ')),
            ],
            options={
                'verbose_name': '倉庫マスタ',
                'verbose_name_plural': '倉庫マスタ',
            },
        ),
        migrations.AlterModelOptions(
            name='arrivalschedule',
            options={'verbose_name': '入荷予定・発注残', 'verbose_name_plural': '入荷予定・発注残'},
        ),
        migrations.AlterField(
            model_name='inventory',
            name='current_quantity',
            field=models.IntegerField(default=0, verbose_name='現在庫数（全倉庫合算）'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='safety_stock',
            field=models.IntegerField(default=20, verbose_name='安全在庫数'),
        ),
        migrations.CreateModel(
            name='WarehouseInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='在庫数')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='商品')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse', verbose_name='倉庫')),
            ],
            options={
                'verbose_name': '倉庫別在庫',
                'verbose_name_plural': '倉庫別在庫',
                'unique_together': {('product', 'warehouse')},
            },
        ),
    ]
