# Generated by Django 6.0.5 on 2026-06-10 06:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_warehouse_alter_arrivalschedule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='inventory_date',
            field=models.DateField(blank=True, default=datetime.date(2026, 5, 31), null=True, verbose_name='棚卸日'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='is_transit',
            field=models.BooleanField(default=False, verbose_name='移動中フラグ'),
        ),
    ]
