# Generated by Django 6.0.5 on 2026-06-11 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_inventory_inventory_date_alter_warehouse_is_transit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': '発注計画', 'verbose_name_plural': '発注計画'},
        ),
        migrations.AddField(
            model_name='product',
            name='lot_rule',
            field=models.CharField(choices=[('ROUND_UP_LOT', '常にロット単位での積み上げ（ケース単位切り上げ）'), ('MIN_LOT_ONLY', '最低ロット満たした後は1個単位での積み上げ（バラ混載可）')], default='ROUND_UP_LOT', help_text='最低ロットを超えた際、ケース単位で切り上げるか、1個単位（バラ）で足すかを選択します', max_length=20, verbose_name='超過時積み上げルール'),
        ),
    ]
