# Generated by Django 6.0.5 on 2026-06-15 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_product_is_excluded_alter_product_trend_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='abc_rank',
            field=models.CharField(choices=[('A', 'Aランク（主力・最重要）'), ('B', 'Bランク（定番・中動態）'), ('C', 'Cランク（準定番・低動態）'), ('DEAD', '処分推奨（不動在庫）')], default='C', max_length=10, verbose_name='ABCランク評価'),
        ),
    ]
