# Generated by Django 6.0.5 on 2026-06-15 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_product_allow_dead_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='demand_source',
            field=models.CharField(choices=[('IKUJI', '日本育児'), ('SELECT', 'ペットセレクト')], default='IKUJI', max_length=20, verbose_name='需要参照元売上'),
        ),
        migrations.AddField(
            model_name='product',
            name='owner_company',
            field=models.CharField(choices=[('IKUJI', '日本育児'), ('SELECT', 'ペットセレクト')], default='IKUJI', max_length=20, verbose_name='所有会社'),
        ),
        migrations.AddField(
            model_name='saleshistory',
            name='company',
            field=models.CharField(choices=[('IKUJI', '日本育児'), ('SELECT', 'ペットセレクト')], default='IKUJI', max_length=20, verbose_name='データ所属会社'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='owner_company',
            field=models.CharField(choices=[('IKUJI', '日本育児'), ('SELECT', 'ペットセレクト')], default='IKUJI', max_length=20, verbose_name='所有会社'),
        ),
        migrations.AlterField(
            model_name='product',
            name='allow_dead_order',
            field=models.BooleanField(default=False, verbose_name='処分品発注許可フラグ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_excluded',
            field=models.BooleanField(default=False, verbose_name='管理外フラグ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='lead_time',
            field=models.IntegerField(default=30, verbose_name='リードタイム（日数）'),
        ),
        migrations.AlterField(
            model_name='product',
            name='order_lot',
            field=models.IntegerField(default=1, verbose_name='発注ロット'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='仕仕入先'),
        ),
    ]
