# Generated by Django 6.0.5 on 2026-06-15 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_product_demand_source_product_owner_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=100, verbose_name='倉庫名'),
        ),
        migrations.AlterUniqueTogether(
            name='warehouse',
            unique_together={('name', 'owner_company')},
        ),
    ]
