# Generated by Django 4.2.30 on 2026-06-19 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_product_is_discontinued'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard', models.CharField(choices=[('planning', '在庫・発注計画'), ('product_master', '商品マスタ登録'), ('sales_history', '日次販売履歴'), ('arrivals', '入荷予定・発注残'), ('valuation', '棚卸資産評価')], max_length=30, verbose_name='対象Dashboard')),
                ('import_type', models.CharField(max_length=50, verbose_name='取込種別')),
                ('status', models.CharField(choices=[('success', '成功'), ('warning', '警告あり'), ('error', '失敗')], max_length=10, verbose_name='結果')),
                ('company', models.CharField(blank=True, default='', max_length=20, verbose_name='対象会社')),
                ('filename', models.CharField(blank=True, default='', max_length=255, verbose_name='ファイル名')),
                ('summary', models.CharField(max_length=255, verbose_name='概要')),
                ('details', models.TextField(blank=True, default='', verbose_name='詳細')),
                ('error_count', models.IntegerField(default=0, verbose_name='エラー件数')),
                ('warning_count', models.IntegerField(default=0, verbose_name='警告件数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='記録日時')),
            ],
            options={
                'verbose_name': '取込ログ',
                'verbose_name_plural': '取込ログ',
                'ordering': ['-created_at'],
            },
        ),
    ]
