# Generated by Django 4.2.30 on 2026-06-22 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_importlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesImportSkip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_rows', models.CharField(blank=True, default='', max_length=100, verbose_name='元データ行')),
                ('reason', models.CharField(max_length=100, verbose_name='スキップ理由')),
                ('sold_date_text', models.CharField(blank=True, default='', max_length=50, verbose_name='伝票日付')),
                ('customer_code', models.CharField(blank=True, default='', max_length=100, verbose_name='得意先コード')),
                ('source_product_code', models.CharField(blank=True, default='', max_length=100, verbose_name='元商品コード')),
                ('normalized_product_code', models.CharField(blank=True, default='', max_length=50, verbose_name='正規化商品コード')),
                ('product_name', models.CharField(blank=True, default='', max_length=255, verbose_name='商品名')),
                ('sales_category', models.CharField(blank=True, default='', max_length=50, verbose_name='区分')),
                ('quantity_text', models.CharField(blank=True, default='', max_length=50, verbose_name='数量')),
                ('tax_excluded_amount_text', models.CharField(blank=True, default='', max_length=50, verbose_name='税抜金額')),
                ('gross_profit_amount_text', models.CharField(blank=True, default='', max_length=50, verbose_name='粗利金額')),
                ('import_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_skips', to='inventory.importlog', verbose_name='取込ログ')),
            ],
            options={
                'verbose_name': '販売履歴取込スキップ明細',
                'verbose_name_plural': '販売履歴取込スキップ明細',
                'ordering': ['id'],
            },
        ),
    ]
