# Generated by Django 4.2.30 on 2026-06-23 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_salesimportskip'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_from_sales_history',
            field=models.BooleanField(default=False, verbose_name='販売履歴CSVから自動生成'),
        ),
        migrations.AddField(
            model_name='product',
            name='first_sales_history_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='販売履歴CSV初回生成日時'),
        ),
    ]
