# Generated by Django 4.2.30 on 2026-06-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_product_created_from_sales_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='運用中フラグ'),
        ),
    ]
