# Generated by Django 4.2.30 on 2026-06-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_standardize_warehouse_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='lead_time',
            field=models.IntegerField(default=90, verbose_name='リードタイム（日数）'),
        ),
    ]
