# Generated by Django 4.2.30 on 2026-06-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_alter_product_lead_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentschedule',
            name='destination',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='向け先'),
        ),
    ]
