# Generated by Django 4.2.30 on 2026-06-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_shipmentschedule_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleshistory',
            name='is_advance_order',
            field=models.BooleanField(default=False, verbose_name='先付け受注（需要計算から除外）'),
        ),
    ]
