# Generated by Django 4.2.30 on 2026-06-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_saleshistory_is_advance_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order_interval_days',
            field=models.PositiveIntegerField(default=0, verbose_name='分割発注間隔（日）'),
        ),
        migrations.AddField(
            model_name='order',
            name='expected_arrival_date',
            field=models.DateField(blank=True, null=True, verbose_name='入荷予定日'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateField(blank=True, null=True, verbose_name='発注予定日'),
        ),
    ]
