# Generated by Django 4.2.30 on 2026-06-24 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_product_order_interval_days_and_order_dates'),
    ]

    operations = [
        migrations.CreateModel(
            name='AkachanOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(choices=[('IKUJI', '日本育児'), ('SELECT', 'ペットセレクト')], default='IKUJI', max_length=20, verbose_name='取込会社')),
                ('external_order_number', models.CharField(max_length=20, unique=True, verbose_name='発注番号')),
                ('invoice_number', models.CharField(blank=True, default='', max_length=30, verbose_name='伝票番号')),
                ('vendor_code', models.CharField(blank=True, default='', max_length=20, verbose_name='取引先コード')),
                ('vendor_name', models.CharField(blank=True, default='', max_length=100, verbose_name='取引先名')),
                ('order_date', models.DateField(blank=True, null=True, verbose_name='受注日')),
                ('shipment_date', models.DateField(blank=True, null=True, verbose_name='出荷日')),
                ('store_delivery_date', models.DateField(blank=True, null=True, verbose_name='店舗納品日')),
                ('center_delivery_date', models.DateField(blank=True, null=True, verbose_name='センター納品日')),
                ('center_code', models.CharField(blank=True, default='', max_length=30, verbose_name='センターコード')),
                ('center_name', models.CharField(blank=True, default='', max_length=100, verbose_name='センター名')),
                ('store_code', models.CharField(blank=True, default='', max_length=30, verbose_name='店舗コード')),
                ('store_name', models.CharField(blank=True, default='', max_length=100, verbose_name='店舗名')),
                ('category_code', models.CharField(blank=True, default='', max_length=20, verbose_name='分類コード')),
                ('category_name', models.CharField(blank=True, default='', max_length=100, verbose_name='分類名')),
                ('source_filename', models.CharField(blank=True, default='', max_length=255, verbose_name='取込ファイル名')),
                ('imported_at', models.DateTimeField(auto_now=True, verbose_name='最終取込日時')),
            ],
            options={
                'verbose_name': '赤ちゃん本舗受注',
                'verbose_name_plural': '赤ちゃん本舗受注',
                'ordering': ['center_delivery_date', 'external_order_number'],
            },
        ),
        migrations.AddField(
            model_name='productvariant',
            name='package_size',
            field=models.IntegerField(default=0, verbose_name='赤本梱包才数'),
        ),
        migrations.AlterField(
            model_name='importlog',
            name='dashboard',
            field=models.CharField(choices=[('planning', '在庫・発注計画'), ('product_master', '商品マスタ登録'), ('sales_history', '日次販売履歴'), ('arrivals', '入荷予定・発注残'), ('valuation', '棚卸資産評価'), ('akachan_orders', '赤ちゃん本舗受注')], max_length=30, verbose_name='対象Dashboard'),
        ),
        migrations.CreateModel(
            name='AkachanOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField(verbose_name='明細番号')),
                ('state_code', models.CharField(blank=True, default='', max_length=3, verbose_name='状態コード')),
                ('source_product_code', models.CharField(blank=True, default='', max_length=20, verbose_name='EDI商品コード')),
                ('jan_code', models.CharField(blank=True, default='', max_length=30, verbose_name='JANコード')),
                ('source_product_name', models.CharField(blank=True, default='', max_length=255, verbose_name='EDI商品名')),
                ('requested_quantity', models.IntegerField(default=0, verbose_name='受注数')),
                ('available_quantity', models.IntegerField(default=0, verbose_name='引当前在庫')),
                ('allocated_quantity', models.IntegerField(default=0, verbose_name='出荷数量')),
                ('stock_status', models.CharField(choices=[('available', '在庫あり'), ('shortage', '不足'), ('out_of_stock', '欠品'), ('unmatched', '商品未登録')], default='unmatched', max_length=20, verbose_name='在庫判定')),
                ('decision', models.CharField(choices=[('pending', '未処理'), ('ship_all', '全量出荷'), ('ship_partial', '一部出荷'), ('out_of_stock', '欠品'), ('hold', '保留')], default='pending', max_length=20, verbose_name='手動処理')),
                ('shortage_reason', models.CharField(blank=True, default='', max_length=255, verbose_name='欠品理由')),
                ('packing_number', models.CharField(blank=True, default='', max_length=6, verbose_name='荷番（6桁）')),
                ('package_size', models.IntegerField(default=0, verbose_name='梱包才数')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.akachanorder', verbose_name='赤ちゃん本舗受注')),
                ('planning_shipment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='akachan_order_line', to='inventory.shipmentschedule', verbose_name='発注計画反映')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '赤ちゃん本舗受注明細',
                'verbose_name_plural': '赤ちゃん本舗受注明細',
                'ordering': ['order__center_delivery_date', 'order__external_order_number', 'line_number'],
                'unique_together': {('order', 'line_number')},
            },
        ),
    ]
