# Generated by Django 4.2.30 on 2026-06-24 04:02

from django.db import migrations


def remove_akachan_planning_shipments(apps, schema_editor):
    AkachanOrderLine = apps.get_model('inventory', 'AkachanOrderLine')
    ShipmentSchedule = apps.get_model('inventory', 'ShipmentSchedule')
    shipment_ids = list(
        AkachanOrderLine.objects.exclude(planning_shipment_id=None)
        .values_list('planning_shipment_id', flat=True)
    )
    ShipmentSchedule.objects.filter(id__in=shipment_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_akachanorder_productvariant_package_size_and_more'),
    ]

    operations = [
        migrations.RunPython(remove_akachan_planning_shipments, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='akachanorderline',
            name='planning_shipment',
        ),
    ]
