# Generated by Django 4.2.30 on 2026-06-24 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_remove_akachanorderline_planning_shipment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='akachanorderline',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='akachanorderline',
            name='order',
        ),
        migrations.RemoveField(
            model_name='akachanorderline',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='package_size',
        ),
        migrations.AlterField(
            model_name='importlog',
            name='dashboard',
            field=models.CharField(choices=[('planning', '在庫・発注計画'), ('product_master', '商品マスタ登録'), ('sales_history', '日次販売履歴'), ('arrivals', '入荷予定・発注残'), ('valuation', '棚卸資産評価')], max_length=30, verbose_name='対象Dashboard'),
        ),
        migrations.DeleteModel(
            name='AkachanOrder',
        ),
        migrations.DeleteModel(
            name='AkachanOrderLine',
        ),
    ]
