# Generated by Django 6.0.5 on 2026-06-10 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_arrivalschedule_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arrivalschedule',
            options={'verbose_name': '入荷予定·発注残', 'verbose_name_plural': '入荷予定·発注残'},
        ),
        migrations.AlterField(
            model_name='inventory',
            name='current_quantity',
            field=models.IntegerField(default=0, help_text='直近の棚卸日（確定日）に計上された実在庫数', verbose_name='現在庫数'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='safety_stock',
            field=models.IntegerField(default=20, help_text='下回ってはならない最低限の守備在庫数', verbose_name='安全在庫数'),
        ),
        migrations.AlterField(
            model_name='product',
            name='lead_time',
            field=models.IntegerField(default=30, help_text='発注してから倉庫に届くまでにかかる日数', verbose_name='リードタイム（日数）'),
        ),
        migrations.AlterField(
            model_name='product',
            name='order_lot',
            field=models.IntegerField(default=1, help_text='最低発注単位・ロット数', verbose_name='発注ロット'),
        ),
    ]
