# Generated by Django 6.0.5 on 2026-06-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_order_options_product_lot_rule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arrivalschedule',
            options={},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AlterModelOptions(
            name='saleshistory',
            options={'verbose_name': '日次販売履歴', 'verbose_name_plural': '日次販売履歴'},
        ),
        migrations.AlterModelOptions(
            name='shipmentschedule',
            options={},
        ),
        migrations.AddField(
            model_name='product',
            name='trend_days',
            field=models.IntegerField(choices=[(90, '90日間（約3ヶ月）'), (120, '120日間（約4ヶ月）'), (150, '150日間（約5ヶ月）'), (180, '180日間（半年）')], default=90, verbose_name='長期トレンド計算日数'),
        ),
        migrations.AlterField(
            model_name='product',
            name='lot_rule',
            field=models.CharField(choices=[('ROUND_UP_LOT', '常にロット単位での積み上げ（ケース単位切り上げ）'), ('MIN_LOT_ONLY', '最低ロット満たした後は1個単位での積み上げ（バラ混載可）')], default='ROUND_UP_LOT', max_length=20, verbose_name='超過時積み上げルール'),
        ),
        migrations.AlterField(
            model_name='product',
            name='trend_max',
            field=models.FloatField(default=2.0, verbose_name='トレンド上限'),
        ),
        migrations.AlterField(
            model_name='product',
            name='trend_min',
            field=models.FloatField(default=0.5, verbose_name='トレンド下限'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='倉庫名'),
        ),
    ]
