# Generated by Django 6.0.5 on 2026-06-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_arrivalschedule_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_excluded',
            field=models.BooleanField(default=False, help_text='チェックを入れるとダッシュボードの計算・表示から完全に除外されます', verbose_name='管理外フラグ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='trend_days',
            field=models.IntegerField(choices=[(90, '90日間（標準）'), (120, '120日間（約4ヶ月）'), (150, '150日間（約5ヶ月）'), (180, '180日間（半年）')], default=90, verbose_name='長期トレンド計算日数'),
        ),
    ]
