# Generated by Django 6.0.5 on 2026-06-15 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_product_abc_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allow_dead_order',
            field=models.BooleanField(default=False, help_text='チェックを入れると処分推奨品であっても自動計算発注ボタンを表示します', verbose_name='処分品発注許可フラグ'),
        ),
    ]
