# Generated by Django 6.0.5 on 2026-06-17 06:32

import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_warehouse_name_alter_warehouse_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='inventory_date',
            field=models.DateField(blank=True, default=inventory.models.last_month_end, null=True, verbose_name='棚卸日'),
        ),
    ]
